version: '3.8'

services:
  video-relay:
    image: bluenviron/mediamtx:latest
    container_name: video-relay
    ports:
      - "8554:8554"

  video-source:
    build: ./video-source
    container_name: video-source
    depends_on:
      - video-relay
    volumes:
      - ./data/sample.mp4:/sample.mp4

  video-processor:
    build: ./video-processor
    container_name: video-processor
    depends_on:
      - video-relay
    volumes:
      - video-data:/app/frames

  spark-job:
    build: ./spark-jobs
    container_name: spark-job
    environment:
      - HOME=/tmp
    volumes:
      - video-data:/app/frames

volumes:
  video-data:

