version: '3.8'

services:
  video-relay:
    image: bluenviron/mediamtx:latest
    container_name: video-relay
    ports:
      - "8554:8554"

  video-source:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.video-source
    container_name: video-source
    depends_on:
      - video-relay
    volumes:
      - ./data:/data

  video-processor:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.video-processor
    container_name: video-processor
    depends_on:
      - video-relay
    volumes:
      - video-data:/app/frames

  spark-job:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.spark-jobs
    container_name: spark-job
    environment:
      - HOME=/tmp
    ports:
      - "4040:4040"
    volumes:
      - video-data:/app/frames

volumes:
  video-data:

