version: '3.8'

services:
  relay-server:
    image: bluenviron/mediamtx:latest
    container_name: relay-server
    ports:
      - "8554:8554"

  image-producer:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.image-producer
    container_name: image-producer
    depends_on:
      - relay-server
    environment:
      - RTSP_URL=rtsp://relay-server:8554/image-stream

  image-consumer:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.image-consumer
    container_name: image-consumer
    depends_on:
      - relay-server
    environment:
      - RTSP_URL=rtsp://relay-server:8554/image-stream
    volumes:
      - ./data:/app/frames

  image-annotator:
    build:
      context: .
      dockerfile: build/docker/Dockerfile.image-annotator
    container_name: image-annotator
    environment:
      - HOME=/tmp
    ports:
      - "4040:4040"
    volumes:
      - ./data:/app/frames

