version: '3.8'

services:
  video-relay:
    image: bluenviron/mediamtx:latest
    container_name: video-relay
    ports:
      - "8554:8554"

  video-source:
    build: ./video-source
    container_name: video-source
    depends_on:
      - video-relay
    volumes:
      - ./data/sample.mp4:/sample.mp4

  video-processor:
    build: ./video-processor
    container_name: video-processor
    depends_on:
      - video-source
    volumes:
      - video-data:/app/frames

  spark-job:
    image: apache/spark:3.5.0
    container_name: spark-job
    entrypoint: [
      "/opt/spark/bin/spark-submit",
      "--master", "local[*]",
      "--conf", "spark.driver.extraJavaOptions=-Dlog4j.configuration=file:/opt/app/log4j2.properties",
      "--conf", "spark.executor.extraJavaOptions=-Dlog4j.configuration=file:/opt/app/log4j.properties",
      "/opt/app/frame-processor.py"
    ]
    environment:
      - HOME=/tmp
    volumes:
      - video-data:/app/frames
      - ./spark-jobs:/opt/app
      - ./spark-checkpoints:/opt/app/checkpoints


volumes:
  video-data:
